name: Build and publish Docker images

on:
  push:
    branches:
      - chore/github-actions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"${version}",
                   "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/release-notes-generator",
                      "@semantic-release/changelog",
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branches: 'chore/github-actions'
          semantic_version: 17.2.2
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.0
            @semantic-release/changelog@5.0.0
            @semantic-release/github@7.0.7
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Application environments
        run: |
          echo '
          VUE_APP_DOMAIN_PROD=api.cryptobot.germainlefebvre.fr
          VUE_APP_NAME=Cryptobot
          '> .env
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FRONTEND_ENV: production
        with:
          name: germainlefebvre4/cryptobot-front
          buildargs: FRONTEND_ENV
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "${{ steps.semantic.outputs.new_release_version }}"

      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     repository: germainlefebvre4/cryptobot-front
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD2 }}
      #     readme-filepath: ./docs/dockerhub/README.md
