name: Deploy

on: 
  workflow_dispatch:
    inputs:
      release:
        description: Release name
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy helm chart
        run: echo Deploy