name: Deploy

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        run: echo Deploy